#!/usr/bin/env node
import { createServer } from "../src/createServer/createServer.js";
import { connectToMyWalletRpc } from "../src/connectToMyWalletRpc.js";
import { doMultisigImport } from "../src/doMultisigImport.js";
import { getConfig } from "../src/getConfig/getConfig.js";

const config = getConfig();
const wallet = await connectToMyWalletRpc(config);
createServer({ ...config, wallet });

await doMultisigImport({ ...config, wallet });

console.log("Successfully imported multisig data!");
console.log("Keeping server open, press CTRL+C to quite");
