#!/bin/bash

# Check if both arguments are provided
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: $0 <wallet name> <method>"
  exit 1
fi

WALLET_NAME=$1
WALLET_PASSWORD=""

WALLET_PATH=./wallets/$WALLET_NAME
PORT=$(cat $WALLET_PATH/port-rpc)
METHOD=$2

curl http://localhost:$PORT/json_rpc \
  -d '{"jsonrpc":"2.0","id":"0","method":"'$METHOD'"}' \
  -H 'Content-Type: application/json'
